//------------------------------------------------------------------------------
// <auto-generated>
//     This code is generated by a software tool.
//     Runtime Environment Version: 4.0.30319.42000
//
//     Changes to this file may cause misbehavior and will be lost if 
//     the code is re-created.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnblockIP_forIPBan.Properties
{
    /// <summary>
    ///   Strongly-typed resource class for searching localized strings, etc.
    /// </summary>
    // This class was automatically generated by the StronglyTypedResourceBuilder
    // class using tools such as ResGen or Visual Studio.
    // To add or remove a member, modify the .ResX file, then restart ResGen
    // with the /str parameter or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnblockIP_forIPBan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the CurrentUICulture property of the current thread for all
        ///   resource lookups using this strongly-typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
